VimPEG Parser for CSV
---------------------

_alpha, demo_

This is a demonstration of the VimPEG PEG parser generator library. As
such, this plugin depends on https://github.com/dahu/Vimpeg[]

NOTE: VimPEG is _NO_ speed daemon. Even parsing a hundred line CSV
file will take half a dozen seconds or more. This is quite
unacceptable for anything other than toy CSV files.

It provides the following rudimentary CSV operations:

* `CSV_Parse(first, last)` for parsing a range of CSV lines in the
  current buffer and returning the data as an array of arrays.
* `CSV_Print(data, separator)` for printing an array of arrays as CSV
  data to the current buffer.
* `CSV_Separator(separator)` for altering the CSV Parser's separator
  (default=',').
* `CSV_Column()` is a standalone function for those who find the
  statusbar _feature_ too cumbersome (it is a bit of a process hog).

NOTE: To disable the automatic inclusion of the column information in
your `statusline`, add the following line to your `~/.vimrc`:

  let g:vimpeg_parser_csv_statusline = 0
